name: flutter_google_wallet
description: A Flutter Google Wallet Plugin
version: 0.1.1
homepage: https://github.com/voyages-sncf-technologies/flutter_google_wallet

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pigeon: ^10.0.0
  flutter_svg: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.6.1
  golden_toolkit: ^0.15.0
  melos: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.flutter_google_wallet
        pluginClass: FlutterGoogleWalletPlugin

  assets:
    - lib/assets/svg/button/

flutter_intl:
  enabled: true
  class_name: I18nGoogleWallet
  main_locale: fr
